server:
  port: 8092
  error:
    include-message: always
    incluse-binding-errors: always
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    spring.sql.init.platform: h2
    username: sa
    password:

  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false