server:
  port: 8093
  error:
    include-message: always
    incluse-binding-errors: always
spring:
  datasource:
    url: jdbc:h2:mem:shoppinDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    spring.sql.init.platform: h2
    username: sa
    password:
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
    
      
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5P} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

resilience4j.circuitbreaker:
    instances:
        producCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        customerCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        incluse: "*"